# Workflow name
name: Project Continuous Integration

# When workflow triggers
on:
  pull_request:
    branches: main

# What workflow does
jobs:
  # Testing PR
  test_pull_request:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test